import sharp from 'sharp';

export default async function handler(req, res) {
    // Add CORS headers to prevent cross-origin 500 blocks
    res.setHeader('Access-Control-Allow-Credentials', true);
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
    res.setHeader(
        'Access-Control-Allow-Headers',
        'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version'
    );

    // Pre-flight request check
    if (req.method === 'OPTIONS') {
        return res.status(200).end();
    }

    if (req.method !== "POST") {
        return res.status(405).json({ error: "Method not allowed" });
    }

    const { prompt } = req.body;
    
    if (!prompt) {
        return res.status(400).json({ error: "Missing prompt payload" });
    }

    const apiKey = process.env.GEMINI_API_KEY;

    // Fix 1: Properly catch missing API key and inform frontend
    if (!apiKey) {
        return res.status(500).json({ error: "Missing GEMINI_API_KEY in Vercel Environment Variables" });
    }

    // --- BRAINROT MODIFIER INJECTION ---
    // A massive list of stupidly chaotic, cursed, and brainrot-themed modifiers (SCRUBBED OF UI/EMOJIS/TEXT)
    const brainrotModifiers = [
        "deep fried meme aesthetic with glowing red laser eyes",
        "dark cursed negative aura energy",
        "sigma male gigachad energy covered in cursed jade rot",
        "holding a bowl of bing chilling while doing the griddy",
        "skibidi toilet escaping from an ancient cursed Ming dynasty vase",
        "hyper-saturated phonk music album cover aesthetic",
        "subway surfers gameplay floating in the background",
        "cursed 2004 flip phone picture quality mixed with 8k hyperrealism",
        "glitchcore aesthetic with corrupted pixels",
        "John Cena floating in the mossy rot with a deep fried red filter",
        "looks like a chaotic shitpost with overwhelming visual noise and 1000% contrast",
        "uncanny valley PS1 graphics mixed with cursed digital decay",
        "grimace shake spilling over an ancient terracotta soldier",
        "fake red arrows and circles pointing at nothing in particular",
        "max aura level 10000 mafia boss dragon",
        "mewing chiseled jawline ancient emperor",
        "looks like a 144p dashcam video of a cryptid",
        "distorted bass-boosted visual effect",
        "looks like it was generated by a schizophrenic AI from 2008",
        "Family Guy funny moments clip floating ominously in the sky",
        "low taper fade haircut on a mythological beast",
        "Super Idol smiling brightly in a cursed 144p low-resolution void",
        "The Wok giving the eyebrow raise in a decaying cyberpunk alley",
        "flashing neon lotuses in a cursed aesthetic",
        "counterfeit Gucci drip on a traditional Chinese guardian lion",
        "looks like a corrupted 2012 creepypasta found footage from rural China",
        "uncanny valley hyper-realistic Pepe the Frog dressed as a Qing dynasty scholar",
        "Minecraft parkour gameplay faintly visible in the bottom half of the image",
        "cursed 3D text reading '$CHINESEROT' rotating like a Windows 95 screensaver",
        "doge dog face superimposed on a mythological qilin",
        "looks like a heavily pixelated cursed image from the deep web",
        "extreme fisheye lens perspective with way too much chromatic aberration",
        "a corrupted JPEG compression artifact nightmare",
        "looks like a fever dream sponsored by Raid Shadow Legends",
        "giant red glowing laser eyes beaming through the digital rot"
    ];

    // Randomly select 4-6 modifiers for maximum unpredictability
    const shuffle = (array) => array.sort(() => 0.5 - Math.random());
    const numModifiers = Math.floor(Math.random() * 3) + 4; // Picks 4, 5, or 6 items
    const selectedBrainrot = shuffle(brainrotModifiers).slice(0, numModifiers);
    
    // Combine the user's frontend prompt with the absurd backend modifiers
    const enhancedPrompt = `${prompt}. Add these specific visual elements to make it stupidly chaotic and cursed: ${selectedBrainrot.join(", ")}. Completely embrace the 'chineserot' deep-fried internet brainrot meme aesthetic. CRITICAL INSTRUCTION: DO NOT generate any emojis, watermarks, UI overlays (no TikTok UI, no LiveLeak), or random text. The ONLY text allowed anywhere in the image is the ticker '$CHINESEROT' seamlessly integrated into the scene.`;

    try {
        // Updated to use Gemini 4.0 (imagen-4.0-generate-001)
        const response = await fetch(
            `https://generativelanguage.googleapis.com/v1beta/models/imagen-4.0-generate-001:predict?key=${apiKey}`,
            {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: JSON.stringify({
                    instances: [
                        { prompt: enhancedPrompt }
                    ],
                    parameters: {
                        sampleCount: 1
                    }
                })
            }
        );

        const data = await response.json();

        // Fix 3: Bubble up exact Google API errors (like bad keys or safety triggers)
        if (!response.ok) {
            return res.status(500).json({
                error: "Google API rejected the request",
                raw: data
            });
        }

        const imageBase64 = data?.predictions?.[0]?.bytesBase64Encoded;

        if (!imageBase64) {
            return res.status(500).json({
                error: "No image returned from Google",
                raw: data
            });
        }

        try {
            // Convert the raw base64 PNG string into a Buffer
            const imageBuffer = Buffer.from(imageBase64, 'base64');
            
            // Compress and convert the image to WebP format
            // We scale it down to a max width/height of 1024px and use 80% quality
            // This easily brings the image size from >1MB down to ~100-200KB
            const compressedBuffer = await sharp(imageBuffer)
                .resize({ width: 1024, height: 1024, fit: 'inside', withoutEnlargement: true })
                .webp({ quality: 80 })
                .toBuffer();

            const compressedBase64 = compressedBuffer.toString('base64');

            // Send the smaller WebP back to the frontend instead of the PNG
            return res.status(200).json({
                image: `data:image/webp;base64,${compressedBase64}`
            });
            
        } catch (compressionError) {
            return res.status(500).json({
                error: "Failed to compress image to WebP",
                message: compressionError.message
            });
        }

    } catch (error) {
        return res.status(500).json({
            error: "Internal Server Error during fetch",
            message: error.message
        });
    }
}
